version: 2.1

jobs:
  build:
    parallelism: 1
    docker:
    - image: circleci/ruby:2.4.10-node
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_TOKEN
      environment:
        BUNDLE_JOBS: 3
        BUNDLE_RETRY: 3
        BUNDLE_PATH: vendor/bundle
        PGHOST: 127.0.0.1
        PGUSER: circleci-db-user
        RAILS_ENV: test
        TZ: "Europe/London"
    - image: circleci/postgres:10.8-alpine
      auth:
        username: $DOCKERHUB_USER
        password: $DOCKERHUB_TOKEN
      environment:
        POSTGRES_USER: circleci-db-user
        POSTGRES_DB: lofi_lions_test
        POSTGRES_PASSWORD: ""
    steps:
    - checkout

      # Which version of bundler?
    - run:
        name: Which bundler?
        command: bundle -v

      # Restore bundle cache
    - restore_cache:
        keys:
        - lofilions-bundle-v2-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        - lofilions-bundle-v2-{{ .Branch }}-
        - lofilions-bundle-v2-master-
        - lofilions-bundle-v2-
        - lofilions-bundle-v1-
    - run:
        name: Bundle Install
        command: bundle check || bundle install

      # Store bundle cache
    - save_cache:
        key: lofilions-bundle-v2-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
        paths:
        - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
#    - restore_cache:
#        keys:
#        - lofilions-yarn-{{ checksum "yarn.lock" }}
#        - lofilions-yarn-

#    - run:
#        name: Yarn Install
#        command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
#    - save_cache:
#        key: lofilions-yarn-{{ checksum "yarn.lock" }}
#        paths:
#        - ~/.cache/yarn

    - run:
        name: Wait for DB
        command: dockerize -wait tcp://localhost:5432 -timeout 1m

    - run:
        name: Database setup
        command: |
          bundle exec rake db:create --trace
          bundle exec rake db:schema:load --trace

    - run:
        name: Run rspec in parallel
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

    - run:
        name: Bundle audit
        command: |
          bundle exec bundle-audit update
          bin/bundle-audit-local --verbose

      # Save test results for timing analysis
    - store_test_results:
        path: test_results

    - store_artifacts:
        path: tmp/capybara
        destination: screenshots

workflows:
  commit:
    jobs:
      - build:
          context: docker-auth
  nightly:
    triggers:
      - schedule:
          cron: "0 2 * * 1" # every monday at 2am
          filters:
            branches:
              only:
                - main
    jobs:
      - build:
          context: docker-auth

