development:
  adapter: postgresql
  database: lofilions_development
  username: lofilions-user
  password:
  host: localhost
  encoding: utf8

test:
  adapter: postgresql
  database: lofilions_test
  username: lofilions-user
  password:
  host: localhost
  encoding: utf8
